name: recipe_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  unicons: ^2.1.1
  cached_network_image: ^3.3.0
  sizer: ^2.0.15 # Important: ensure `flutter pub get` succeeds
  google_fonts: ^6.1.0 # Match this version with any native references (e.g., in build.gradle) to avoid issues
  image_picker: ^1.0.4
  http: ^1.1.0
  shared_preferences: ^2.2.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/beverage.png
    - assets/cake.png
    - assets/coffee.png
    - assets/dish.png
    - assets/fruits.png
    - assets/lunch-box.png
    - assets/recipebook.gif
    - assets/logo.jpg
